# Generated by Django 4.2.7 on 2025-10-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_download_count'),
        ('api', '0002_alter_resource_file'),
    ]

    operations = [
    ]
